name: 打包前端并部署到服务器
on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 读取仓库内容
        uses: actions/checkout@master

      - name: 安装nodejs
        uses: actions/setup-node@master

      - name: 安装依赖
        run: npm install
      - name: 打包
        run: npm run build
      - name: 将dist文件复制到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "dist"
          target: "/www/wwwroot"
